name: Generate UML
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate-uml:
    name: 'Generate UML'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - run: dotnet tool install --global PlantUmlClassDiagramGenerator --version 1.2.4
      - run: dotnet tool restore

      - name: Remove old diagrams 
        run: rm -r ./UML || true
        
      - name: Check if there is code
        run: |
          [ -d "./Assets/Scripts/" ] && echo "::set-output name=CODE_EXISTS::$('true')" || true
        id: check_for_code
      - name: Create a folder for diagrams
        if: ${{ steps.check_for_code.outputs.CODE_EXISTS == 'true' }}
        run: mkdir ./UML
      - name: Generate PlantUML files
        if: ${{ steps.check_for_code.outputs.CODE_EXISTS == 'true' }}
        run: puml-gen ./Assets/Scripts/ ./UML -dir -public -createAssociation -allInOne
        
      - name: Get File names
        if: ${{ steps.check_for_code.outputs.CODE_EXISTS == 'true' }}
        run: |
          echo "::set-output name=UML_FILES::$(find ./UML -name "*.puml" | tr '\n' ' ')"
        id: get_file_names
      - name: Generate SVG Diagrams
        if: ${{ steps.check_for_code.outputs.CODE_EXISTS == 'true' }}
        uses: cloudbees/plantuml-github-action@master
        with:
          args: -v -tsvg ${{ steps.get_file_names.outputs.UML_FILES }}

      - uses: EndBug/add-and-commit@v7.0.0
        with:
          author_name: 'UML Bot'
          message: 'Generate UML (${{ github.workflow }})'
          author_email: 41898282+uml-bot[bot]@users.noreply.github.com