name: Generate UML
on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  generate-uml:
    name: 'Generate UML'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - run: dotnet tool install --global PlantUmlClassDiagramGenerator --version 1.2.4
      - run: dotnet tool restore

      - name: Remove old diagrams 
        run: rm -r ./UML || true 
      - name: Create a folder for diagrams
        run: mkdir ./UML
      - name: Generate PlantUML files
        run: puml-gen ./Assets/Scripts/ ./UML -dir -public -createAssociation -allInOne
        
      - name: Get File names
        run: |
          echo "::set-output name=UML_FILES::$(find ./UML -name "*.puml")"
        id: file_names
      - name: Generate SVG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
          args: -v -tsvg ${{ steps.file_names.UML_FILES }}

      - uses: EndBug/add-and-commit@v7.0.0
        with:
          author_name: 'UML Bot'
          message: 'Generate UML (${{ github.workflow }})'
          author_email: 41898282+uml-bot[bot]@users.noreply.github.com