name: Generate UML
on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  generate-uml:
    name: 'Generate UML'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.x
      - run: dotnet tool install --global PlantUmlClassDiagramGenerator --version 1.2.4
      - run: dotnet tool restore
      - run: puml-gen . -public
      - uses: EndBug/add-and-commit@v7.0.0
        with:
          author_name: 'UML Bot'
          message: 'Generate UML (${{ github.workflow }})'
          author_email: 41898282+uml-bot[bot]@users.noreply.github.com